### ISSUE TITLE
PUT request on existing patient creates new guarantor on each PUT request. 

### ISSUE THREAD

**Issue by thapaasanjay** [athenahealth/apiserver-athenaFlex#210]
**Description**
PUT request on existing patient creates new guarantor on each PUT request

Make a PUT request to the  Patient Resource api,  for instance "https://fhir-server-name/fhir/Patient/1534261098000720" and you will see that the value is changed in reference. You have to make at least 2 request in order to see the serious bug which has a very severity.
```yaml
        {
            "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-patientAsGuarantor",
            "valueBoolean": true
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-guarantorDetails",
            "valueReference": {
                "reference": "RelatedPerson/G-228966_1534261098000720"
            }
        }
```

The complete body for the  PUT request is 
```yaml
{
    "resourceType": "Patient",
    "id": "1534261098000720",
    "meta": {
        "lastUpdated": "2021-09-30T14:35:49.990-05:00",
        "profile": [
            "http://hl7.org/fhir/StructureDefinition/daf-patient",
            "http://hl7.org/fhir/StructureDefinition/ge-patient-profile.html"
        ],
        "security": [
            {
                "system": "http://www.hl7.org/fhir/v3/Confidentiality",
                "code": "N",
                "display": "Normal"
            }
        ]
    },
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\">Patient Kane CPSI Jr F DOB: 2000/07/25</td><td width=\"42%\">899 Desiard St Suite D West Monroe, LA 71291 USA Phone: 3185555555 Phone: 3185550000 Phone: 3185555555 Email: testpatient13@outlook.com</td></tr></tbody></table></div>"
    },
    "extension": [
        {
            "url": "http://hl7.org/fhir/StructureDefinition/us-core-race",
            "valueCodeableConcept": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/v3/Race",
                        "code": "2028-9",
                        "display": "Asian"
                    }
                ]
            }
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/us-core-race",
            "valueCodeableConcept": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/v3/Race",
                        "code": "2106-3",
                        "display": "White"
                    }
                ]
            }
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/us-core-ethnicity",
            "valueCodeableConcept": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/v3/Ethnicity",
                        "code": "2186-5",
                        "display": "Not Hispanic or Latino"
                    }
                ]
            }
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-RESPPROVID",
            "valueReference": {
                "reference": "Practitioner/1521041700000010"
            }
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-REFDOCID",
            "valueReference": {
                "reference": "Practitioner/1575189783000010"
            }
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-preferredContact",
            "valueString": "E-mail"
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthTime",
            "valueDateTime": "2000-07-25T00:00:00-05:00"
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-patientAsGuarantor",
            "valueBoolean": true
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/ge-patient-extension-guarantorDetails",
            "valueReference": {
                "reference": "RelatedPerson/G-228966_1534261098000720"
            }
        },
        {
            "url": "http://fhir.org/guides/argonaut/StructureDefinition/argo-race",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "http://hl7.org/fhir/v3/Race",
                        "code": "2028-9",
                        "display": "Asian"
                    }
                },
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "http://hl7.org/fhir/v3/Race",
                        "code": "2106-3",
                        "display": "White"
                    }
                }
            ]
        },
        {
            "url": "http://fhir.org/guides/argonaut/StructureDefinition/argo-ethnicity",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "http://hl7.org/fhir/v3/Ethnicity",
                        "code": "2186-5",
                        "display": "Not Hispanic or Latino"
                    }
                }
            ]
        },
        {
            "url": "http://fhir.org/guides/argonaut/StructureDefinition/argo-birthsex",
            "valueCode": "F"
        }
    ],
    "identifier": [
        {
            "type": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/v2/0203",
                        "code": "PI"
                    }
                ]
            },
            "system": "http://www.gehealthcare.com/fhir/cpsemr/namingsystem/PatientId/1000-11746-9749",
            "value": "test2"
        },
        {
            "use": "secondary",
            "type": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/identifier-type",
                        "code": "SB"
                    }
                ]
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "111223456"
        }
    ],
    "active": true,
    "name": [
        {
            "use": "official",
            "family": [
                "CPSI"
            ],
            "given": [
                "Patient",
                "Kane"
            ],
            "suffix": [
                "Jr"
            ]
        },
        {
            "use": "nickname",
            "given": [
                "Patient"
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "value": "3185555555",
            "use": "work"
        },
        {
            "system": "phone",
            "value": "3185550000",
            "use": "home"
        },
        {
            "system": "phone",
            "value": "3185555555",
            "use": "mobile"
        },
        {
            "system": "email",
            "value": "testpatient13@outlook.com"
        }
    ],
    "gender": "female",
    "_gender": {
        "extension": [
            {
                "url": "http://hl7.org/fhir/StructureDefinition/ge-originalCode",
                "valueCoding": {
                    "system": "http://www.gehealthcare.com/fhir/cpsemr/codesystem/gender",
                    "code": "F",
                    "display": "Female"
                }
            }
        ]
    },
    "birthDate": "2000-07-25",
    "deceasedBoolean": false,
    "address": [
        {
            "line": [
                "8990 Desiard St",
                "Suite D"
            ],
            "city": "West Monroe",
            "state": "LA",
            "postalCode": "71291",
            "country": "USA"
        }
    ],
    "maritalStatus": {
        "coding": [
            {
                "system": "http://hl7.org/fhir/v3/MaritalStatus",
                "code": "D",
                "display": "Divorced"
            }
        ],
        "text": "Divorced"
    },
    "careProvider": [
        {
            "reference": "Practitioner/1784545729436250"
        }
    ],
    "managingOrganization": {
        "reference": "Organization/LO-1750937045815010"
    }
}
```

**Additional context**
My problem is exactly same as this one: https://github.com/athenahealth/apiserver-athenaFlex/issues/96, but this problem has **never been addressed for more than 2 years.** Please do not close this issue without resolving it.
